# See https://github.com/golangci/golangci-lint#config-file
run:
  issues-exit-code: 1 #Default
  tests: true #Default

linters:
  enable:
  disable:
    - misspell
    - errcheck
    - goimports
    - gofmt

# Commented out in 1.18 b/c generics, to restore when functional
# Note the two exclusions below still apply when this is restored.
#   - revive

issues:
  exclude-rules:
    # helpers in tests often (rightfully) pass a *testing.T as their first argument
    - path: _test\.go
      text: "context.Context should be the first parameter of a function"
      linters:
        - revive
    # Yes, they are, but it's okay in a test
    - path: _test\.go
      text: "exported func.*returns unexported type.*which can be annoying to use"
      linters:
        - revive

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - cancelled
