version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  disable:
    - errcheck
    - misspell
  settings:
    misspell:
      locale: US
      ignore-rules:
        - cancelled
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: _test\.go
        text: context.Context should be the first parameter of a function
      - linters:
          - revive
        path: _test\.go
        text: exported func.*returns unexported type.*which can be annoying to use
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
