// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package sdkinstrument

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyncCounter-0]
	_ = x[SyncUpDownCounter-1]
	_ = x[SyncGauge-2]
	_ = x[SyncHistogram-3]
	_ = x[AsyncCounter-4]
	_ = x[AsyncUpDownCounter-5]
	_ = x[AsyncGauge-6]
	_ = x[NumKinds-7]
}

const _Kind_name = "SyncCounterSyncUpDownCounterSyncGaugeSyncHistogramAsyncCounterAsyncUpDownCounterAsyncGaugeNumKinds"

var _Kind_index = [...]uint8{0, 11, 28, 37, 50, 62, 80, 90, 98}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
