#!/bin/sh

# dev-jmacd in staging
# export LS_ACCESS_TOKEN=42f288975e1b8048d49ff5214d0359b2
# export LS_SERVICE_NAME=v10
# export OTEL_EXPORTER_OTLP_METRIC_TEMPORALITY_PREFERENCE=delta
# export OTEL_EXPORTER_OTLP_SPAN_ENDPOINT=ingest.staging.lightstep.com:443
# export OTEL_EXPORTER_OTLP_SPAN_INSECURE=false
# export OTEL_EXPORTER_OTLP_METRIC_ENDPOINT=ingest.staging.lightstep.com:443
# export OTEL_EXPORTER_OTLP_METRIC_INSECURE=false
# export OTEL_EXPORTER_OTLP_METRIC_PERIOD=10s

export LS_ACCESS_TOKEN=42f288975e1b8048d49ff5214d0359b2
export LS_SERVICE_NAME=hello

export OTEL_EXPORTER_OTLP_METRIC_TEMPORALITY_PREFERENCE=delta
export OTEL_EXPORTER_OTLP_SPAN_ENDPOINT=127.0.0.1:4317
export OTEL_EXPORTER_OTLP_SPAN_INSECURE=true
export OTEL_EXPORTER_OTLP_METRIC_ENDPOINT=127.0.0.1:4317
export OTEL_EXPORTER_OTLP_METRIC_INSECURE=true
export OTEL_EXPORTER_OTLP_METRIC_PERIOD=10s

go run .
